### PR TITLE
Close #1

### LINKED ISSUE #1: Create dummy data
Create objects folder with individual geojson files representing map features (markers, lines, polygons). Assign custom properties and description to each object.

### PR DESCRIPTION
**Pull request by zimmicz**
Added several features to the repo and hopefully fixed your "get story" button issue.
Regarding the HTML parsing: there's a neat little directive called [v-html](https://vuejs.org/v2/api/#v-html) that directly updates the element's innerHTML with provided text. However, as clearly stated in the docs, the directive should not be used on user-provided content.

Yet I can imagine some html whitelist including just the <a data-url=""></a> element. Or some completely different solution to this issue.

### CODE REVIEW

**Comment by mattesCZ** [comment]
Good job!

**Comment by zimmicz** [comment]
@mattesCZ what's next?

**Comment by mattesCZ** [comment]
I'd like to look into the scrolling/mapmove thing. You can try to load the features in the story and display in the map if you like. Do you think we should create issues for this or it's just an unnecessary bureaucracy at this stage?

**Comment by zimmicz** [comment]
@mattesCZ I don't insist on creating issues. However, I would like to reach agreement on the following:
* should we switch the current naive implementation of the map for the Vue2Leaflet? I vote yea. Once done, we could split the tasks more easily I guess.
* should we load all the data during the page load, or when user scrolls to the given section? I vote for the first option to implement MVP asap.
* could we agree on the way that clicking the link would change the map state? I propose to keep the current zoom level and recenter the map to the feature position.

UPDATE: after spending a few minutes searching this conversation, I guess it might be beneficial to create issues (if just for the related chat).

**Comment by mattesCZ** [comment]
@zimmicz 

- Create issues -- yes, it can be useful for discussions. Let's create it when we expect some discussion but not necessarily for everything
- vue2leaflet :+1: 
- Load all immediately :+1:
- Clicking -- not sure about it, I'd vote for some marker "bounce" rather than mam move. But mapmove is easier to implement.

**Comment by zimmicz** [comment]
@mattesCZ what if the marker is outside the visible part of the map? Should we move the map and bounce the marker?

**Comment by mattesCZ** [comment]
@zimmicz I like the way mapy.cz does that -- show pin and distance on the side of the map in the direction of the "hidden" marker. They use it for selected address etc., but we can use it on mouseover.

**Comment by zimmicz** [comment]
@mattesCZ I can't find the use case you're talking about at mapy.cz. Anyway, to make it clear (especially to myself):
* when I hover the link in the text, the map doesn't move and an indicator saying "100 kms from your current location" is shown?
* when I click the link, does viewport change to the given location and the marker starts bouncing, or does the map stand still? I feel a bit confused here.
* what should happen when user clicks the map marker?

Here's my proposal:
* nothing happens when you hover the link (at least for now, we're still talking MVP, don't forget)
* when you click the link **and its twin marker is not in the visible viewport**, map recenters on the given location and the marker bounces
* when you click the link **and its twin marker is in the visible viewport**, map doesn't move at all and the marker bounces

I hope we reach agreement on this real soon. The only thing I'm a 100 % sure about is that zoom level shouldn't change no matter what you do.

**Comment by zimmicz** [comment]
@mattesCZ FYI I failed to add marker bouncing with vue2leaflet with `<l-marker>` and `<l-icon>` components, so I asked about it at https://github.com/KoRiGaN/Vue2Leaflet/issues/212. Hope to hear from the author soon. I think it would be possible to implement this with two different `L.Icon` instances, using animated GIF for the bouncing one, yet it feels a bit hackish. I'll keep you posted.

**Pull request merged**
